apiVersion: v2
name: fortigate-prometheus-exporter
description: Helm chart for prometheus-community/fortigate_exporter
type: application
version: 0.3.1
appVersion: 1.25.0
home: "https://github.com/claudsonm/fortigate-prometheus-exporter-helm"
sources:
  - "https://github.com/claudsonm/fortigate-prometheus-exporter-helm"
  - "https://github.com/prometheus-community/fortigate_exporter"
maintainers:
  - name: claudsonm
    url: "https://github.com/claudsonm"
annotations:
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/license: "MIT"
  artifacthub.io/maintainers: |
    - name: Claudson Martins
      email: claudson@outlook.com