apiVersion: v2
name: fortigate-exporter
description: Helm chart for prometheus-community/fortigate_exporter
type: application
version: 0.1.0
appVersion: "main"
home: "https://github.com/claudsonm/fortigate-exporter-helm-chart"
sources:
  - "https://github.com/claudsonm/fortigate-exporter-helm-chart"
  - "https://github.com/prometheus-community/fortigate_exporter"
maintainers:
  - name: claudsonm
    url: "https://github.com/claudsonm"
annotations:
  artifacthub.io/images: |
    - name: fortigate-exporter
      image: quay.io/prometheuscommunity/fortigate-exporter:main-distroless
  artifacthub.io/category: "monitoring"
  artifacthub.io/license: "MIT"