replicaCount: 1

image:
  repository: quay.io/prometheuscommunity/fortigate-exporter
  pullPolicy: IfNotPresent
  tag: "main-distroless"

config:
  targetUrl: ""
  insecureSkipVerify: false
  probes: {}

exporter:
  scrapeTimeout: 30
  httpsTimeout: 10
  insecure: false
  maxBgpPaths: 10000
  maxVpnUsers: 0

auth:
  existingSecret: ""
  secretKey: "token"

hostAliases: []

service:
  enabled: false
  type: ClusterIP
  port: 9710

serviceMonitor:
  enabled: false
  targetUrl: ""
  interval: 30s
  scrapeTimeout: 10s
  labels: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []