apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fortigate-exporter.fullname" . }}
  labels:
    {{- include "fortigate-exporter.labels" . | nindent 4 }}
data:
  fortigate-key.yaml.tmpl: |
    "{{ required "config.targetUrl is required" .Values.config.targetUrl }}":
      token: "__FORTIGATE_TOKEN__"
      {{- if .Values.config.insecureSkipVerify }}
      insecure_skip_verify: {{ .Values.config.insecureSkipVerify }}
      {{- end }}
      {{- if .Values.config.probes }}
      probes:
        {{- toYaml .Values.config.probes | nindent 8 }}
      {{- end }}